server:
  port: 58060
  error:
    path: /error
  servlet:
    context-path: /article-publisher
    session:
      tracking-modes: cookie
      timeout: 3H
      cookie:
        http-only: true
    application-display-name: article-publisher
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: article-publisher-测试环境
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      suffix: .jsp
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
      deserialization:
        accept_empty_string_as_null_object: true
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.172:3306/article-publisher?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 200
      max-wait: 60000
      min-evictable-idle-time-millis: 1800000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 600000
      remove-abandoned: true
      remove-abandoned-timeout-millis: 1800000
      log-abandoned: true
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
          config:
            multi-statement-allow: true
            none-base-statement-allow: true
        log4j:
          enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        url-pattern: /admin/druid/*
        reset-enable: true
  messages:
    basename: i18n/message
    encoding: utf-8
  freemarker:
    #req访问request
    request-context-attribute: req
    #后缀名
    suffix: .ftl
    content-type: text/html; charset=UTF-8
    enabled: true
    #缓存配置
    cache: false
    #模板加载路径 按需配置
    template-loader-path: classpath:templates/, file:./templates/
    charset: UTF-8 #编码格式
    expose-spring-macro-helpers: true
    settings:
      #数字格式化，无小数点
      number_format: '0.##'
      auto_import: spring.ftl as spring
      default_encoding: UTF-8
      output_encoding: UTF-8

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.chqiuu.publisher
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn